### ISSUE TITLE
Feature Request: LinkedIn

### ISSUE THREAD

**Issue by mikestecker** [engram-design/SocialPoster#1]
Would love to post to LinkedIn as well using [Dukt's LinkedIn plugin](https://github.com/dukt/craft-linkedin)

I see it show up but when I try and connect, I see the error:

`Class 'League\OAuth2\Client\Provider\Linkedin' not found`

**Comment by engram-design** [comment]
Added in [1.1.0 release](https://github.com/engram-design/SocialPoster/releases/tag/1.1.0)
