### ISSUE TITLE
"Date Tweeted" column for entry index page

### ISSUE THREAD

**Issue by lindseydiloreto** [engram-design/SocialPoster#10]
What's the best way to view the "Date Tweeted" on the entry index page?

I'm about to make a dynamic column for it, but that doesn't feel like it's the right permanent answer. I'm wondering if some kind of fieldtype would be the right solution there.

**Comment by engram-design** [comment]
As in - have it appear in the Entry index as a column?

**Comment by lindseydiloreto** [comment]
Yeah, exactly.

I whipped up a quick solution, seems to be working pretty well... Just submitted a PR for it. (#15)

Hope that helps, lemme know if you have any questions!
