### ISSUE TITLE
Supported social media sites

### ISSUE THREAD

**Issue by Datcood** [engram-design/SocialPoster#17]
Hi silly question, which exact social media sites are supported as of today ?

In Wiki documentation FAQ it says Twitter and Facebook -
https://github.com/engram-design/SocialPoster/wiki/04.-FAQs
_> Can I post to any social media channel?
> At the moment, only Facebook and Twitter is supported, with plans to support everything that the Dukt OAuth plugin does._

However below screenshot shows TW, FB, LinkedIn, Google,Vimeo

https://github.com/engram-design/SocialPoster/blob/master/screenshots/providers.png

Thanks in advance

**Comment by engram-design** [comment]
Moved into proper docs - https://verbb.io/craft-plugins/social-poster/docs
