### ISSUE TITLE
Facebook API v2.11 is throwing a 400 Bad Request

### ISSUE THREAD

**Issue by JRetza** [engram-design/SocialPoster#19]
### Description
When using this plugin with a newly created Facebook App (API v2.11) an error is thrown on post.

### Steps to reproduce

1. Create a new Facebook App as normal using the latest API 2.11
2. Configure your OAuth & Social Poster plugins, attempt to use for Facebook
3. 400 Bad Request Error 

### Additional info

- Plugin version: OAuth 2.1.1 & Social Poster 1.2.2
- Craft version: 2.6.2994

The only way we could get this to work was to spin up an old testing app in Facebook that was using API v2.5 - we updated the API to v2.8 and everything functions as normal. Unfortunately, you cannot 'downgrade' the version of the FB API you come in on - so if you make a new FB App today - you can only use API v2.11 (which throws the error described above).

**Comment by engram-design** [comment]
Should be improved in [2.0.0](https://github.com/verbb/social-poster/releases/tag/2.0.0), but please there are [potential issues with Facebook](https://github.com/verbb/social-poster#facebook-compatibility)
