### ISSUE TITLE
Feature Request: Add support to post to Facebook Pages

### ISSUE THREAD

**Issue by mikestecker** [engram-design/SocialPoster#2]
It appears that social poster only posts to the connected user's feed rather than being able to post as a page they manage. It would be great to be able to post as the page instead so it remains part of the overall brand of the website.

**Comment by engram-design** [comment]
Added in [1.1.0 release](https://github.com/engram-design/SocialPoster/releases/tag/1.1.0).

**Comment by mikestecker** [comment]
@engram-design I see the option to toggle whether to post to a timeline or page, but how do you actually select which page to post to? I've tried toggling it to page and posting, but it still posts to my personal timeline.
