### ISSUE TITLE
Class 'League\OAuth2\Client\Provider\Linkedin' not found

### ISSUE THREAD

**Issue by Saboteur777** [engram-design/SocialPoster#20]
### Description

Got a `Class 'League\OAuth2\Client\Provider\Linkedin' not found` error when trying to connect to LinkedIn. 

### Steps to reproduce

1. Set up OAuth
2. Try to connect @ `/admin/socialposter/accounts/linkedin`

### Additional info

- Plugin version: 1.2.2
- Craft version: 2.6.2997

**Comment by engram-design** [comment]
Should be fixed in [2.0.0](https://github.com/verbb/social-poster/releases/tag/2.0.0).
