### ISSUE TITLE
Posting to a users Facebook "page" throws error - 400 Bad Request Error

### ISSUE THREAD

**Issue by ghost** [engram-design/SocialPoster#22]
### Description
Posting directly to a Facebook "**profile**" works without any issues. However trying to configure the plugin to post to a users "**page**" rather than their "**profile**" throws the following error:

Could not post to Facebook. Error: {"statusCode":400,"reasonPhrase":"Bad Request"}.

I've done some digging around and some people seem to suggest that the plugin doesn't work with any Facebook API version greater than v2.8. However I only experience this issue when posting to a users "**page**" rather than their "**profile**". 

Source: https://craftcms.stackexchange.com/questions/20689/social-poster-getting-403-error 

Unfortunately I can't roll the Facebook API to any version other than v2.12 as this Facebook app was created today.

### Steps to reproduce

1. Install and configure plugin
2. During configuration - under "**Facebook Post Type**" select "**Page**" and add your **Facebook Page ID**
3. Finally when saving an entry and trying to post to Facebook it won't work and will show the error

### Additional info

- Plugin version: 1.2.2
- Oauth plugin Version:  2.1.1
- Craft version: 2.6.3012
- Facebook API version: 2.12

**Comment by bfjare** [comment]
Confirming I have this issue as well.

**Comment by bartrylant** [comment]
Same issue here. Not able anymore to post to Facebook pages.

**Comment by engram-design** [comment]
Sorry for the delay all, this has been addressed in the Craft 3 version (a priority) and will back-date this fix soon.

**Comment by engram-design** [comment]
Should be improved in [2.0.0](https://github.com/verbb/social-poster/releases/tag/2.0.0), but please there are [potential issues with Facebook](https://github.com/verbb/social-poster#facebook-compatibility)
