### ISSUE TITLE
duplicate posts when entry is enabled for multiple sites

### ISSUE THREAD

**Issue by geoffreyvandamme** [engram-design/SocialPoster#28]
Hi guys,

I'm experiencing a small issue with the social poster plugin:
I'll try to sketch what is happening;

I'm working with a craft multisite setup containing 3 websites: 
- website-A that groups all news items from the other 2 websites; these newsitems have to be available on website-A to, so I have to enable them for this website in order to have a url for them here (tried with the new multisite query feature, but then there's no link available for this website)
- Website-B and Website-C that generate the newsitems

The problem is that when i want to post a newsitem to facebook, it gets posted double, because a newsitem exists on Website-B and get propagated to Website-A,

I have been trying to find a solution for this problem for a while now, but with no luck,

Do you guys know a workaround for this?

Greets,

Geoffrey

- Plugin version: 2.0.8
- Craft version: Craft Pro 3.3.3

**Comment by engram-design** [comment]
Fixed in [2.0.9](https://github.com/verbb/social-poster/releases/tag/2.0.9)
