### ISSUE TITLE
Duplicate posts on FB page

### ISSUE THREAD

**Issue by proximo7** [engram-design/SocialPoster#29]
We are seeing duplicate posts on a Facebook page after saving an entry while using the "Post to Facebook".

I've tried re-entering all credentials, re-connecting to Facebook, updating Craft (3.3.18), etc. Nothing seems to work. Initially the plugin posts 2 Facebook posts at a time when a new post is created. Later, for some reason, it starts posting about 8 Facebook posts every time.
 
- Plugin version: 2.0.8
- Craft version: 3.3.18 (not multisite)

**Comment by engram-design** [comment]
Fixed in [2.0.9](https://github.com/verbb/social-poster/releases/tag/2.0.9)
