### ISSUE TITLE
LinkedIn "w_share" permission now deprecated - w_member_social new permission

### ISSUE THREAD

**Issue by JoshC96** [engram-design/SocialPoster#33]
### Description
I've connected my LinkedIn app to Social poster and when connecting I get an error in the logs:
"'Scope 'w_share' is not authorized for your application'"
Did some digging and LinkedIn have updated their API permission names, these can be found here: https://docs.microsoft.com/en-us/linkedin/shared/references/migrations/marketing-permissions-migration?context=linkedin/marketing/context

### Steps to reproduce

1. Add linkedin application, request marketing developer permissions
2. Connect to social poster per docs
3. Hit "connect" button on LinkedIn 'New Account' setup process.

### Additional info

- Plugin version: 2.1.0
- Craft version: 3.4.15

**Comment by engram-design** [comment]
Yep, will be in the next release https://github.com/verbb/social-poster/commit/9c87d83fec69643b9e695caf5a3c994b2e7dfa4f

**Comment by engram-design** [comment]
Fixed in [2.1.1](https://github.com/verbb/social-poster/releases/tag/2.1.1).
