### ISSUE TITLE
Setting Unknown Property Error

### ISSUE THREAD

**Issue by masonry47** [engram-design/SocialPoster#37]
### Describe the bug

Hi there!

We are having an issue when creating entries (a local environment).  We have successfully configured Facebook as a Provider and successfully connected an "account" (which is a Facebook page).  When attempting to create a new entry for an "enabled" section we get:

 `An exception has been thrown during the rendering of a template ("Setting unknown property: craft\elements\Entry::provider"). in /var/www/html/vendor/verbb/social-poster/src/templates/_includes/entry-sidebar.html:87`

Thanks in advance for any ideas!

### Steps to reproduce

1. Configure Facebook Provider
2. Create and Connect Facebook page as an account
3. Enable Section in Plugin Settings
4. Create Entry in that section

### Craft CMS version

4.2.5.2

### Plugin version

3.0.0-beta.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.0](https://github.com/verbb/social-poster/releases/tag/3.0.0)
