### ISSUE TITLE
Account Save Error

### ISSUE THREAD

**Issue by masonry47** [engram-design/SocialPoster#38]
### Describe the bug

Thanks for the fix on this issue [here](https://github.com/verbb/social-poster/issues/37).  After updating that did the trick on that one but we are now seeing a new issue when adding an account. We see this after when trying to save a new account.

`verbb\socialposter\services\Accounts::getAccountById(): Argument #1 ($id) must be of type int, null given, called in /var/www/html/vendor/verbb/social-poster/src/controllers/AccountsController.php on line 111`

Thanks!

### Steps to reproduce

1. Configure Facebook Provider
2. Go to accounts > new account
3. Hit save after filling out required info.

### Craft CMS version

4.2.5.2

### Plugin version

3.0.0

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed in [3.0.1](https://github.com/verbb/social-poster/releases/tag/3.0.1)
