### ISSUE TITLE
 Only owners of the URL have the ability...

### ISSUE THREAD

**Issue by masonry47** [engram-design/SocialPoster#40]
### Describe the bug

Hi there!

We are having issues posting the image.  When using that field we get  

` (#100) Only owners of the URL have the ability to specify the picture, name, thumbnail or description params.`

I saw the previous issue here

https://github.com/verbb/social-poster/issues/23

So we did go through and successfully verify our domain, but still get the error. 

An ideas on that? (We can successfully post when not using the image field in the Account Setup.)

Thanks!

### Steps to reproduce

1. 
2. 

### Craft CMS version

 4.3.0

### Plugin version

dev-craft-4 as 3.0.1

**Comment by engram-design** [comment]
A few things to confirm:
- Is the URL to your image using the same domain you've verified? For instance, does your site use local asset volumes? If using S3 or others, this will be a different URL to the site domain.
- It wasn't obvious to me, but I had to click "Add Asset" in Facebook Business Manager and add the page to the verified domain
    - https://share.cleanshot.com/VYP7W5
    - https://share.cleanshot.com/HlbmSW
- Try adding the site's URL, or the image URL in https://developers.facebook.com/tools/debug/ (be sure to scrape the info if not done yet) 
- If you're using a Link in the post, it should be the same domain as the image.
