### ISSUE TITLE
Missing side bar in entries editor

### ISSUE THREAD

**Issue by joshparylak** [engram-design/SocialPoster#41]
### Describe the bug

The default Craft sidebar containing the options to edit the slug, author, postdate, entry date, and status disappear when the plugin is enabled and at least one account is added. Occurred both locally with the plugin not fully configured (picture) and on production, with the plugin fully configured and posting correctly.

<img width="719" alt="Screen Shot 2022-12-08 at 8 45 11 AM" src="https://user-images.githubusercontent.com/39498787/206461911-83c27a0c-e352-4639-a164-06f56a1bcafe.png">

### Steps to reproduce

1. Install and enable Social Poster
2. Add at least one account

### Craft CMS version

4.3.4

### Plugin version

3.0.1

### Multi-site?

No

### Additional context

The site has SEOMatic installed, which also adds content to the entry sidebar. I tried disabling that plugin to see if it was possibly conflicting, but the problem remained. No errors appear in the browser console. No errors in any Craft logs.

**Comment by engram-design** [comment]
Should be fixed in [3.0.2](https://github.com/verbb/social-poster/releases/tag/3.0.2)

**Comment by mijewe** [comment]
I'm still having this issue in 4.0.1

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/social-poster:"dev-craft-4 as 4.0.1"`.
