### ISSUE TITLE
Typo in event-documentation

### ISSUE THREAD

**Issue by tom-bywild** [engram-design/SocialPoster#42]
### Describe the bug

The documentation for the event-API assigns the event to `$e` in the function header, but accesses it as `$event` ([link](https://verbb.io/craft-plugins/social-poster/docs/developers/events))

### Steps to reproduce

1. Visit link
2. See error

### Craft CMS version

-

### Plugin version

-

**Comment by engram-design** [comment]
Thanks, should be updated now.
