### ISSUE TITLE
Cannot get Facebook Page ID

### ISSUE THREAD

**Issue by TomDeSmet** [engram-design/SocialPoster#46]
### Describe the bug

I followed al steps to connect to faceBook. It all worked, I've setup a Facebook page with my account, I connected to Social Poster to the Facebook Page, but when I come back to Craft CMS and it says connected, the Page ID is still empty.
If I press the reload button, I get an Axios 500 error.

The error in the `social-poster.log` file says:
```
Facebook: API error: “{"error":{"message":"Unsupported get request. Object with ID 'v15.0me' does not exist, cannot be loaded due to missing permissions, or does not support this operation.
```

### Steps to reproduce

1. Connect to a Facebook page.
2. Try to reload the Page ID dropdown.

### Craft CMS version

4.x

### Plugin version

4.0

### Multi-site?

No

**Comment by engram-design** [comment]
Looks like this was an issue with the [auth](https://github.com/verbb/auth/releases/tag/1.0.1) module and normalizing the base URL for Facebook. If you run `composer update` or `composer require verbb/auth` that should get the latest version of that.
