### ISSUE TITLE
Facebook page id not showing up

### ISSUE THREAD

**Issue by eddiedale** [engram-design/SocialPoster#48]
### Describe the bug

I have an issue on an all-up-to-date craft install, also with the latest verbb/auth, seemingly related to https://github.com/verbb/social-poster/issues/46

Groups show up, but pages not. Even though I am administrator of the pages I allow while connecting.

When I connect, it also shows up that the app needs to be approved. I have tried with multiple apps, following the docs, with the same result every time.

<img width="515" alt="image" src="https://github.com/verbb/social-poster/assets/995836/e269b3cb-037c-42e2-a871-fb926b8f9f9b">

<img width="242" alt="image" src="https://github.com/verbb/social-poster/assets/995836/ba6ba1f8-de8f-4dbe-ae84-56ac2cccc282">

### Steps to reproduce

1. New Craft install with Social Poster
2. Set up a Facebook app according to the docs: https://verbb.io/craft-plugins/social-poster/docs/providers/facebook#step-2-register-a-facebook-app
3. Connect to Facebook, selecting the page you want to post to
4. See the page ID not being populated.

### Craft CMS version

Craft Pro 4.4.13

### Plugin version

4.0.1

### Multi-site?

No

### Additional context

<img width="1017" alt="image" src="https://github.com/verbb/social-poster/assets/995836/884dd171-1d56-4ca8-a22f-9f217b46aedb">

<img width="1276" alt="image" src="https://github.com/verbb/social-poster/assets/995836/e3244fe0-7fc0-4c5d-b209-c0687d371611">

**Comment by engram-design** [comment]
So, connecting to Facebook all goes okay? It's just after you connect, when you try to select the Facebook Page, there's just nothing to select? The refresh button doesn't do anything (next to the dropdown)?

Anything in your `storage/logs/social-poster-*.log` or `auth-*.log` files?

**Comment by eddiedale** [comment]
Correct.

I just tried one more time with the whole process with the same result.
I do get the warning when connecting:

<img width="595" alt="image" src="https://github.com/verbb/social-poster/assets/995836/55ea19fd-b065-4e8d-982f-d2bf0cd7e005">


<img width="644" alt="image" src="https://github.com/verbb/social-poster/assets/995836/1c866bcc-9d30-428f-be3f-364e9572091a">


<img width="272" alt="image" src="https://github.com/verbb/social-poster/assets/995836/457f70ad-bdbc-4c62-ad55-df11a8658522">
  
  

**Groups do show up however:**
<img width="250" alt="image" src="https://github.com/verbb/social-poster/assets/995836/269e5cdb-622a-483b-babb-5e3314933486">

Edit: And unfortunately nothing in either of the log files.

**Comment by engram-design** [comment]
Were there any applicable permissions under "What is verbb-app-test allowed to do?" that should be enabled? I can't recall you needing to approve the app (after a whole heap of testing at the time). I'll do another run-through from scratch.

**Comment by eddiedale** [comment]
No, generally everything is enabled.

If I don't pick any groups in the step before, the "Post content into groups on your behalf" is forced disabled, as in my screenshot, but everything else is enabled.

<img width="616" alt="image" src="https://github.com/verbb/social-poster/assets/995836/35463bfc-d4ba-4591-a4b0-e6157c7cd064">

First time using this plugin, so can't speak for earlier experience.

**Comment by engram-design** [comment]
That all looks perfect to me, particularly the "Show a list of the Pages you manage" is what that endpoint is after. I may have to get you to test a patch release with some extra logging when fetching those pages, but it _should_ be throwing an error (and logging it) if there's an issue, but as you say you've got no error logs.

**Comment by eddiedale** [comment]
Thanks for the response. I definitely don't get anything in my error logs. Tried the process again with same results.

I debugged a little further, and found that I simply received an empty array on the /me/accounts API call.

After trying out the Facebook Graph API Debugger, I found that by adding the "business_management" permission, I got the correct response, and was then also allowed to choose the page in the Social Poster app.

So as a temporary workaround, going via the Graph API to update the token to also have business_management permission solves the problem. 

But yeah, without doing that, I simply do not see any of the pages I choose, even though I have full admin priveleges on the Pages.

**Comment by engram-design** [comment]
Thanks for continuing to troubleshoot this, and that's quite interesting. I'm a little hesitant to include this straight away, because according to the [docs](https://developers.facebook.com/docs/permissions/reference/business_management/) it requires an App Review. 

For now, I've added the ability to set custom scopes in a [config file](https://verbb.io/craft-plugins/social-poster/docs/get-started/configuration#accounts), so you can add this scope for your use case. I'll need to do a bit of research to see if this should be the default for everyone, as it doesn't seem to be the case for a few installs I've tested with, with different degrees of permissions.

Updated for the next release. To get this early, run `composer require verbb/social-poster:"dev-craft-4 as 4.0.3"`

**Comment by eddiedale** [comment]
Great! Thanks for the fix! Sounds like a good solution. :-)
