### ISSUE TITLE
Facebook: Groups API removed

### ISSUE THREAD

**Issue by JeroenJRP** [engram-design/SocialPoster#54]
### Describe the bug

Apparently the Groups API has been removed from Facebook for all API versions starting April 22, 2024: https://developers.facebook.com/docs/graph-api/changelog/version19.0/

Personally I don't need to post to a group, but I can't make an OAuth connection using my developer account because the `publish_to_groups` is requested. That gives the following error in the log:
 
```
2024-08-05 10:46:51 [ERROR] Unable to process callback for “facebook”: “An error occurred.” /var/www/html/vendor/verbb/auth/src/base/OAuthProviderTrait.php:176
2024-08-05 10:46:51 [INFO] Request context:
$_GET = [
    'p' => 'social-poster/auth/callback'
    'error_code' => '100'
    'error_message' => 'Invalid Scopes: publish_to_groups. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions'
]

$_POST = []
```

This might not be a problem for accounts outside our organization, but we are unable to test this at the moment.

### Steps to reproduce

1. Add Facebook account
2. Try to connect to Facebook using a Facebook App's developer account.

### Craft CMS version

4.10.7

### Plugin version

4.0.11

### Multi-site?

No

**Comment by engram-design** [comment]
Ah, Facebook - you've done it again. Fixed for the next release. To get this early, run `composer require verbb/social-poster:"dev-craft-4 as 4.0.11"`.

**Comment by engram-design** [comment]
Updated in [4.0.12](https://github.com/verbb/social-poster/releases/tag/4.0.12)
