### ISSUE TITLE
Cannot connect to Facebook

### ISSUE THREAD

**Issue by marijana** [engram-design/SocialPoster#8]
After clicking the "Connect" button in Facebook Social Poster account I get a white page and this error:
"NetworkError: 500 Internal Server Error - http://my.page/index.php/admin/actions/oauth/connect?provider=facebook"

OAuth plugin is configured:
- Client Id and Client Secret are filled
  App is public and configured: 
- Client OAuth Login - is enabled
- Web OAuth Login - is enabled
- Valid OAuth redirect URIs - copied the "Redirect URI" from OAuth Facebook settings page

This is from the oauth.log

---

2016/07/08 10:15:33 [info] [plugin] [Forced] OAuth Connect - Step 1
Array
(
    [referer] => /index.php/admin/actions/socialPoster/oauth/connect?handle=facebook
    [scope] => Array
        (
            [0] => publish_actions
            [1] => manage_pages
            [2] => publish_pages
            [3] => user_managed_groups
            [4] => user_posts
            [5] => user_photos
        )

```
[authorizationOptions] => Array
    (
    )

[redirectTo] => http://my.page/index.php/admin/actions/oauth/connect?provider=facebook
```

)

---

2016/07/08 10:15:33 [info] [plugin] [Forced] OAuth Connect - Step 2A
Array
(
    [handle] => facebook
    [scope] => Array
        (
            [0] => publish_actions
            [1] => manage_pages
            [2] => publish_pages
            [3] => user_managed_groups
            [4] => user_posts
            [5] => user_photos
        )

```
[authorizationOptions] => Array
    (
    )

[referer] => /index.php/admin/actions/socialPoster/oauth/connect?handle=facebook
```

)

---

Also, do I need to submit my Facebook App for approval?

Thanks

**Comment by engram-design** [comment]
Is there anything in, `craft.log`, `phperrors.log` or `socialposter.log`? I don't believe your app needs to be live/approved.

**Comment by marijana** [comment]
Thanks for your quick response!

Nothing in `craft.log` or in `phperrors.log`

I don't even have `socialposter.log` in /craft/storage/runtime/logs

**Comment by engram-design** [comment]
Hmmm, a 500 Internal Server Error usually points to something script-wise, so I wonder if its something to do with your local development? Any chance you've used https://dukt.net/craft/rest, https://dukt.net/craft/facebook, or https://dukt.net/craft/social and come across the same issue when connecting?

**Comment by marijana** [comment]
I didn't use any of those plugins so far but now I installed https://dukt.net/craft/facebook to test it and same thing happened when trying to connect to facebook:
"NetworkError: 500 Internal Server Error - http://my.page/index.php/admin/actions/oauth/connect?provider=facebook"

This is from the facebook.log

---

2016/07/08 16:31:58 [info] [plugin] [Forced] OAuth Connect - Step 1
Array
(
    [referer] => /index.php/admin/actions/facebook/connect
    [scope] => Array
        (
            [0] => public_profile
            [1] => manage_pages
            [2] => read_insights
        )

```
[authorizationOptions] => Array
    (
    )

[redirectTo] => http://my.page/index.php/admin/actions/oauth/connect?provider=facebook
```

)

---

2016/07/08 16:31:58 [info] [plugin] [Forced] OAuth Connect - Step 2A
Array
(
    [handle] => facebook
    [scope] => Array
        (
            [0] => public_profile
            [1] => manage_pages
            [2] => read_insights
        )

```
[authorizationOptions] => Array
    (
    )

[referer] => /index.php/admin/actions/facebook/connect
```

)

---

It seems its only related to facebook because I normally connected to Twitter today with OAuth plugin and SocialPoster plugin.

Any idea where I should start digging for possible culprits?

Many thanks for your help so far!

**Comment by engram-design** [comment]
Yeah, thats interesting, and I wanted to check if it was a Social Poster issue or an OAuth one. Seems like it might be an issue with OAuth. I might recommend posting an issue over at https://github.com/dukt/craft-oauth/issues

**Comment by marijana** [comment]
Will do that, yes.
Thanks for your time and help!
