### ISSUE TITLE
Twig: Check if entry has already been posted?

### ISSUE THREAD

**Issue by lindseydiloreto** [engram-design/SocialPoster#9]
How would you check to see if an entry has already been posted?

I want to add a Twig conditional around my "Post" checkbox on the front-end form.

**Comment by engram-design** [comment]
You'll now be able to as of [1.2.0](https://github.com/engram-design/SocialPoster/releases/tag/1.2.0). Use the new template tag:

```
{% set posts = craft.socialPoster.posts({ element: entry }) %}
```

**Comment by lindseydiloreto** [comment]
Excellent, thanks man! Works like a charm. :)
